# Modelling Classical, probabilistic, and Quantum Systems

## Classical Discrete Systems
![Deterministic System](images/ClassicPhysicalSystem.png)



Modeling the dynamic behaviors and the state of a classical discrete system using matrices and vectors. The state after one click is computed as follows:

$$ 
    \begin{bmatrix} 0 && 0 && 0 && 0 && 0 && 0 \\
                   0 && 0 && 0 && 0 && 0 && 0 \\
                   0 && 1 && 0 && 0 && 0 && 1 \\
                   0 && 0 && 0 && 1 && 0 && 0 \\
                   0 && 0 && 1 && 0 && 0 && 0 \\
                   1 && 0 && 0 && 0 && 1 && 0 \\
    \end{bmatrix}
    \begin{bmatrix} 6 \\
                    2 \\
                    1 \\
                    5 \\
                    3 \\
                    10 \\
    \end{bmatrix}
    =
    \begin{bmatrix} 0 \\
                    0 \\
                    12 \\
                    5 \\
                    1 \\
                    9 \\
    \end{bmatrix}$$

In [2]:
import numpy as np

# Define two 3x3 complex matrices
m1 = np.array([[0,0,0,0,0,0], 
               [0,0,0,0,0,0], 
               [0,1,0,0,0,1],
               [0,0,0,1,0,0], 
               [0,0,1,0,0,0], 
               [1,0,0,0,1,0]])

v1 = np.array([[6], [2], [1], [5], [3], [10]])


print("Input: ", m1,v1)

# Multiplying a 3x3 matrix by a 3x1 vector
state_after_one_click = np.dot(m1, v1)
print("Result after one Click: ", state_after_one_click)

Input:  [[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 1 0 0 0 1]
 [0 0 0 1 0 0]
 [0 0 1 0 0 0]
 [1 0 0 0 1 0]] [[ 6]
 [ 2]
 [ 1]
 [ 5]
 [ 3]
 [10]]
Result after one Click:  [[ 0]
 [ 0]
 [12]
 [ 5]
 [ 1]
 [ 9]]


![State after two clicks.](images/ClassicPhysicalSystem2.png)

The state after two cliks is computed as follows:

In [3]:
print("Result after two clicks: ", np.dot(m1,state_after_one_click))

Result after two clicks:  [[ 0]
 [ 0]
 [ 9]
 [ 5]
 [12]
 [ 1]]


## Exercises 



### Excercise 1:

1. Write a program to model the behavior of the probabilistic double slit example depicted in the figure.
2. Show the results of the experiment using a bar diagram. Each bar represents the intensity of the light at the specific target.


![Probabilistic Double slit.](images/ProbabilisticSystem.png)

In [4]:
import numpy as np

# Definir la matriz de transición según el modelo probabilístico
M = np.array([[0, 0, 0, 0, 0, 0, 0, 0], 
                [1/2, 0, 0, 0, 0, 0, 0, 0], 
                [1/2, 0, 0, 0, 0, 0, 0, 0],
                [0, 1/3, 0, 1, 0, 0, 0, 0], 
                [0, 1/3, 0, 0, 1, 0, 0, 0], 
                [0, 1/3, 1/3, 0, 0, 1, 0, 0],
                [0, 0, 1/3, 0, 0, 0, 1, 0],
                [0, 0, 1/3, 0, 0, 0, 0, 1]])

# Estado inicial (la partícula está en el punto de partida)
X = np.array([1, 0, 0, 0, 0, 0, 0, 0])

# Multiplicamos por la matriz para obtener el estado después de un clic
MmultiX = np.dot(M, X)

# Multiplicamos nuevamente para obtener el estado después de dos clics
MmultiX2 = np.dot(M, MmultiX)

# Mostrar resultados numéricos
print("Estado después de un clic:", MmultiX)
print("Estado después de dos clics:", MmultiX2)

# Representación gráfica simple en texto
def diagram(state):
    max_length = 50  # Máximo número de caracteres para representar la barra más larga
    max_value = max(state)  # Valor máximo de la probabilidad
    
    print("\nDistribución de probabilidades:")
    for i, value in enumerate(state):
        bar_length = int((value / max_value) * max_length)  # Escalar el largo de la barra
        bar = '█' * bar_length  # Usar el caracter '█' para la barra
        print(f"Posición {i}: {bar} ({value:.4f})")  # Mostrar la barra y la probabilidad

# Imprimir la distribución de probabilidades después de dos clics
diagram(MmultiX2)



Estado después de un clic: [0.  0.5 0.5 0.  0.  0.  0.  0. ]
Estado después de dos clics: [0.         0.         0.         0.16666667 0.16666667 0.33333333
 0.16666667 0.16666667]

Distribución de probabilidades:
Posición 0:  (0.0000)
Posición 1:  (0.0000)
Posición 2:  (0.0000)
Posición 3: █████████████████████████ (0.1667)
Posición 4: █████████████████████████ (0.1667)
Posición 5: ██████████████████████████████████████████████████ (0.3333)
Posición 6: █████████████████████████ (0.1667)
Posición 7: █████████████████████████ (0.1667)


### Excercise 2:

1. Write a program to model the behavior of the quantum double slit example depicted in the figure.
2. Show the results of the experiment using a bar diagram. Each bar represents the intensity of the light at the specific target.


![Probabilistic Double slit.](images/QuantumSystem.png)

In [5]:
import numpy as np

# Definir la matriz de transición cuántica 
M = np.array([[0,0,0,0,0,0,0,0], 
               [1/np.sqrt(2),0,0,0,0,0,0,0], 
               [1/np.sqrt(2),0,0,0,0,0,0,0],
               [0,(-1+1j)/1/np.sqrt(6),0,1,0,0,0,0], 
               [0,(-1-1j)/1/np.sqrt(6),0,0,1,0,0,0], 
               [0,(1-1j)/1/np.sqrt(6),(-1+1j)/1/np.sqrt(6),0,0,1,0,0],
               [0,0,(-1-1j)/1/np.sqrt(6),0,0,0,1,0],
               [0,0,(1-1j)/1/np.sqrt(6),0,0,0,0,1]], dtype=complex)

# Estado inicial (la partícula está en el punto de partida)
X = np.array([1, 0, 0, 0, 0, 0, 0, 0], dtype=complex)

# Multiplicamos por la matriz para obtener el estado después de un clic
MmultiX = np.dot(M, X)

# Multiplicamos nuevamente para obtener el estado después de dos clics
MmultiX2 = np.dot(M, MmultiX)

# Mostrar resultados numéricos de amplitudes complejas
print("Amplitud después de un clic:", MmultiX)
print("Amplitud después de dos clics:", MmultiX2)

# Calcular las intensidades (el cuadrado de la magnitud de las amplitudes complejas)
intensities = np.abs(MmultiX2)**2

# Mostrar intensidades
print("\nIntensidades (Probabilidades) después de dos clics:", intensities)

# Representación gráfica simple en texto
def diagram(intensities):
    max_length = 50  # Máximo número de caracteres para representar la barra más larga
    max_value = max(intensities)  # Valor máximo de la intensidad
    
    print("\nDistribución de intensidades:")
    for i, value in enumerate(intensities):
        bar_length = int((value / max_value) * max_length)  # Escalar el largo de la barra
        bar = '█' * bar_length  # Usar el caracter '█' para la barra
        print(f"Posición {i}: {bar} ({value:.4f})")  # Mostrar la barra y la intensidad

# Imprimir la distribución de intensidades después de dos clics
diagram(intensities)


Amplitud después de un clic: [0.        +0.j 0.70710678+0.j 0.70710678+0.j 0.        +0.j
 0.        +0.j 0.        +0.j 0.        +0.j 0.        +0.j]
Amplitud después de dos clics: [ 0.        +0.j          0.        +0.j          0.        +0.j
 -0.28867513+0.28867513j -0.28867513-0.28867513j  0.        +0.j
 -0.28867513-0.28867513j  0.28867513-0.28867513j]

Intensidades (Probabilidades) después de dos clics: [0.         0.         0.         0.16666667 0.16666667 0.
 0.16666667 0.16666667]

Distribución de intensidades:
Posición 0:  (0.0000)
Posición 1:  (0.0000)
Posición 2:  (0.0000)
Posición 3: ██████████████████████████████████████████████████ (0.1667)
Posición 4: ██████████████████████████████████████████████████ (0.1667)
Posición 5:  (0.0000)
Posición 6: ██████████████████████████████████████████████████ (0.1667)
Posición 7: ██████████████████████████████████████████████████ (0.1667)


## Exercise 3: Simulating the Double Slit Experiment with Waves

### Objective

In this exercise, you will create a simulation of the double slit experiment using Python. Unlike particle-based interpretations, you will model light as waves and observe the interference pattern that emerges when waves pass through two slits and overlap on a screen. This simulation will help you visualize how constructive and destructive interference patterns form.

### Background

The double slit experiment demonstrates the wave-particle duality of light and
matter. When coherent light passes through two closely spaced slits, it creates
an interference pattern of bright and dark fringes on a detection screen. This
pattern results from the constructive and destructive interference of the waves
emanating from the slits.

### References

[Mathematics of Interference](https://phys.libretexts.org/Bookshelves/University_Physics/University_Physics_(OpenStax)/University_Physics_III_-_Optics_and_Modern_Physics_(OpenStax)/03%3A_Interference/3.03%3A_Mathematics_of_Interference)

### Task

Your task is to simulate the wave interference pattern using Python. Assume each slit acts as a point source of waves that spread out in circular patterns. When these waves overlap, they interfere with each other, creating a pattern of alternating high and low intensity on a screen.

### Steps

1. **Setup the Environment**: Ensure you have Python installed with the necessary libraries: NumPy for numerical calculations and Matplotlib for plotting.

2. **Define Parameters**:
   - Define the distance between the slits, the wavelength of the light, the distance from the slits to the screen, and the number of points on the screen where intensity will be calculated.

3. **Model the Waves**:
   - For simplicity, you can assume the wavefronts are straight lines perpendicular to the direction of propagation. Use the Huygens-Fresnel principle to model each slit as a source of new waves.

4. **Calculate Intensity**:
   - Use the principle of superposition to calculate the resultant wave amplitude at each point on the screen by summing the contributions from each slit.
   - The intensity of light at each point is proportional to the square of the amplitude of the resultant wave.

5. **Plot the Results**:
   - Plot the calculated intensity pattern on the screen. You should observe a series of bright and dark fringes, demonstrating the interference pattern.

### Hints

- Use NumPy arrays to efficiently calculate the wave amplitudes and intensities across the screen.
- Remember, the phase difference between the waves from the two slits contributes to the constructive (in-phase) and destructive (out-of-phase) interference.

### Sample Code Skeleton




In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Definir parámetros
distancia_rendijas = 0.1  # distancia entre las dos rendijas (en metros)
longitud_onda = 500e-9    # longitud de onda de la luz (500 nm)
distancia_pantalla = 1.0  # distancia de las rendijas a la pantalla (en metros)
ancho_pantalla = 0.5      # ancho de la pantalla (en metros)
num_puntos = 1000         # número de puntos en la pantalla para calcular la intensidad

# Calcular posiciones en la pantalla
puntos_pantalla = np.linspace(-ancho_pantalla/2, ancho_pantalla/2, num_puntos)

# Función para calcular la distancia desde cada rendija hasta el punto en la pantalla
def diferencia_de_camino(x, distancia_rendijas, distancia_pantalla):
    distancia_rendija1 = np.sqrt((distancia_rendijas/2)**2 + distancia_pantalla**2)  # distancia desde la rendija 1
    distancia_rendija2 = np.sqrt((distancia_rendijas/2)**2 + distancia_pantalla**2)  # distancia desde la rendija 2
    return np.sqrt((x + distancia_rendijas/2)**2 + distancia_pantalla**2), np.sqrt((x - distancia_rendijas/2)**2 + distancia_pantalla**2)

# Calcular el patrón de interferencia
intensidad = np.zeros(num_puntos)  # inicializar arreglo de intensidad

for i, x in enumerate(puntos_pantalla):
    r1, r2 = diferencia_de_camino(x, distancia_rendijas, distancia_pantalla)
    
    # Diferencia de fase debido a la diferencia de camino
    diferencia_de_fase = (2 * np.pi / longitud_onda) * (r2 - r1)
    
    # Superposición de ondas de ambas rendijas
    amplitud = np.cos(diferencia_de_fase / 2)
    
    # La intensidad es proporcional al cuadrado de la amplitud
    intensidad[i] = amplitud**2

# Graficar los resultados
plt.figure(figsize=(10, 6))
plt.plot(puntos_pantalla, intensidad, label='Patrón de Interferencia')
plt.xlabel('Posición en la Pantalla (m)')
plt.ylabel('Intensidad')
plt.title('Simulación del Experimento de Doble Rendija: Patrón de Interferencia')
plt.legend()
plt.show()


ModuleNotFoundError: No module named 'matplotlib'